eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${SERVICE_REGISTRY:http://localhost:8761/eureka}

okta:
  oauth2: 
    issuer: https://dev-17138003.okta.com/oauth2/default
    audience: api://default
